
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  cu_on_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./test/linux_run.sh

      - name: Run conan demo
        run: ./conan_demo/run.sh "Hello World!"

  ci_on_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./test/win_run.ps1
        continue-on-error: true
